<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="2" time="0.003">
  <testcase classname="__main__.qa_print_fb" name="test_001_print_bf" time="0.0014">
    <error type="exceptions.ValueError">itemsize mismatch: print_fb0:0 using 4, vector_sink_b0:0 using 1
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "../python/qa_print_fb.py", line 46, in test_001_print_bf
    self.tb.connect(prtfb,dst)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 47, in wrapped
    func(self, src, src_port, dst, dst_port)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 110, in connect
    self.primitive_connect(*args)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 5331, in primitive_connect
    return _runtime_swig.top_block_sptr_primitive_connect(self, *args)
    </error>
  </testcase>
  <testcase classname="__main__.qa_print_fb" name="test_001_t" time="0.0016"></testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
